Repository CoolPeace-yanolza/frontend, pull requests merged in 2024-01, with the labels that each got.

#2 [#1] 스타일테마팔레트 + 라우팅 설정
  package-lock.json
  package.json
  src/App.tsx
  src/routes/index.ts
  src/routes/lib/MainRouter.tsx
  src/styles/theme.ts
  tsconfig.paths.json
Labels: design, chore

#6 [fix] main branch에 이슈 및 PR 템플릿 생성
  .github/issue_template.md
  .github/pull_request_template.md
Labels: fix, doc

#4 [modify] barrel (배럴) 파일 컨벤션 추가 및 일부 주요 폴더 이동
  .github/workflows/dev.yaml
  .github/workflows/preview.yaml
  .github/workflows/production.yaml
  src/api/index.ts
  src/api/lib/getExample.ts
  src/api/lib/instance.ts
  src/components/common/index.tsx
  src/components/index.tsx
  src/constants/index.ts
  src/constants/lib/STATUS_CODES.ts
  src/hooks/index.ts
  src/hooks/lib/useExample.ts
  src/hooks/queries/useGetExample.ts
  src/pages/Example/index.tsx
  src/pages/index.tsx
  src/routes/MainRouter/index.tsx
  src/routes/index.ts
  src/test/exampleCalculate.test.ts
  src/utils/api/index.ts
  src/utils/constants/index.ts
  src/utils/exampleMinus.ts
  src/utils/examplePlus.ts
  src/utils/index.ts
  src/utils/lib/exampleCalculate.ts
  src/utils/test/exampleMinus.test.ts
  src/utils/test/examplePlus.test.ts
Labels: modify, rename, move

#18 [#14] tanStack-query, recoil, react-error-boundary 세팅
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.tsx
  src/components/ErrorFallback/ErrorApp/index.tsx
  src/components/ErrorFallback/index.tsx
  src/components/Loading/LoadingApp/index.tsx
  src/components/Loading/index.tsx
  src/components/index.tsx
Labels: chore

#22 [#15] 레이아웃 피드백 반영
  src/assets/icons/ic-header-user.svg
  src/assets/icons/ic-sidebar-coupon-register.svg
  src/assets/icons/ic-sidebar-coupon.svg
  src/assets/icons/ic-sidebar-settlement.svg
  src/components/common/Layout/Header/Select/index.tsx
  src/components/common/Layout/Header/index.tsx
  src/components/common/Layout/Sidebar/Header/index.tsx
  src/components/common/Layout/Sidebar/Navigation/Coupon/CouponNav/index.tsx
  src/components/common/Layout/Sidebar/Navigation/Coupon/index.tsx
  src/components/common/Layout/Sidebar/Navigation/Settlements/index.tsx
  src/components/common/Layout/Sidebar/Navigation/index.tsx
  src/components/common/Layout/Sidebar/index.tsx
  src/components/common/Layout/index.tsx
  src/types/sidebar.d.ts
  src/types/sidebar.ts
  src/utils/index.ts
  src/utils/lib/toRem.ts
  tsconfig.paths.json
Labels: modify, design

#25 [#24] 1차 야놀자 멘토링 제출용 리드미 작성 doc
  README.md
Labels: doc

#19 [#11] 대시보드 페이지 레이아웃 작업 & 차트 라이브러리 설치
  package-lock.json
  package.json
  src/components/Dashboard/CouponRecommendSection/index.tsx
  src/components/Dashboard/CouponStatusSection/index.tsx
  src/components/Dashboard/DailyReportSection/index.tsx
  src/components/Dashboard/GraphSection/DownloadReport.tsx
  src/components/Dashboard/GraphSection/GraphContainer.tsx
  src/components/Dashboard/GraphSection/index.tsx
  src/components/Dashboard/index.tsx
  src/components/Report/ReportGraphSection/index.tsx
  src/components/Report/index.tsx
  src/components/common/DashboardHeader/index.tsx
  src/components/common/Layout/index.tsx
  src/components/common/index.tsx
  src/pages/Dashboard.tsx/index.tsx
  src/pages/Report.tsx/index.tsx
  src/routes/MainRouter/index.tsx
  src/types/dashboardHeader.ts
Labels: design, chore

#23 [#20] 헤더 선택 숙소 state Recoil atoms로 전달하기 (로그인 구현 전 버전)
  package-lock.json
  package.json
  src/assets/icons/ic-sidebar-hamburger.svg
  src/components/common/Layout/Header/Select/index.tsx
  src/components/common/Layout/Header/index.tsx
  src/components/common/Layout/Sidebar/Header/index.tsx
  src/recoil/atoms/headerAccommodationState.ts
  src/recoil/index.ts
  src/types/header.ts
  tsconfig.paths.json
Labels: feat, modify, chore

#29 [#26] 누적 리포트 레이아웃
  src/assets/icons/ic-catchphrase-rocket.svg
  src/components/Report/LeftSection/Graph/index.tsx
  src/components/Report/LeftSection/YearReport/index.tsx
  src/components/Report/LeftSection/index.tsx
  src/components/Report/ReportGraphSection/index.tsx
  src/components/Report/RightSection/Catchphrase/index.tsx
  src/components/Report/RightSection/TotalReport/index.tsx
  src/components/Report/RightSection/index.tsx
  src/components/Report/index.tsx
  src/components/common/Layout/Sidebar/Header/index.tsx
  src/components/common/Layout/Sidebar/Navigation/Coupon/index.tsx
  src/components/common/Layout/Sidebar/Navigation/CustomNavLink/index.tsx
  src/components/common/Layout/Sidebar/Navigation/Settlements/index.tsx
  src/components/common/Layout/Sidebar/Navigation/index.tsx
  src/components/common/Layout/Sidebar/index.tsx
  src/components/common/Layout/index.tsx
  src/pages/.gitkeep
  src/pages/Report.tsx/index.tsx
  src/pages/Report/index.tsx
  src/routes/MainRouter/index.tsx
  src/types/layout.ts
  src/types/report.ts
  src/utils/index.ts
  src/utils/lib/report.ts
Labels: modify, design

#32 [#10] 쿠폰 조회페이지 레이아웃 구현
  src/assets/icons/ic-couponlist-center.svg
  src/assets/icons/ic-couponlist-expose-expired.svg
  src/assets/icons/ic-couponlist-expose-stop.svg
  src/assets/icons/ic-couponlist-expose-wait.svg
  src/assets/icons/ic-couponlist-expose.svg
  src/assets/icons/ic-couponlist-period-center.svg
  src/assets/icons/ic-couponlist-search.svg
  src/assets/icons/ic-couponlist-speaker.svg
  src/assets/icons/ic-couponlist-toggleOff.svg
  src/assets/icons/ic-couponlist-toggleOn.svg
  src/components/CouponList/CouponBanner/index.tsx
  src/components/CouponList/CouponHeader/index.tsx
  src/components/CouponList/CouponItem/index.tsx
  src/components/CouponList/CouponMain/index.tsx
  src/components/CouponList/CouponNav/index.tsx
  src/components/CouponList/CouponOld/CouponExpired.tsx
  src/components/CouponList/CouponOld/CouponExpose.tsx
  src/components/CouponList/CouponOld/CouponStop.tsx
  src/components/CouponList/CouponOld/CouponWait.tsx
  src/components/CouponList/index.tsx
  src/pages/CouponList/index.tsx
  src/routes/MainRouter/index.tsx
  src/types/couponList.ts
Labels: design

#38 [#28] 대시보드페이지 상세레이아웃 진행
  public/images/ic-dailyReport-status01.png
  public/images/ic-dailyReport-status02.png
  public/images/ic-dailyReport-status03.png
  public/images/ic-dailyReport-status04.png
  public/images/ic-dashboard-couponRate.png
  src/assets/icons/ic-dashboard-arrow.svg
  src/assets/icons/ic-dashboard-bigLocation.svg
  src/assets/icons/ic-dashboard-downloadReport.svg
  src/assets/icons/ic-dashboard-gps.svg
  src/assets/icons/ic-dashboard-location.svg
  src/assets/icons/ic-dashboard-reload.svg
  src/components/Dashboard/CouponRecommendSection/index.tsx
  src/components/Dashboard/CouponStatusSection/StatusItem/index.tsx
  src/components/Dashboard/CouponStatusSection/index.tsx
  src/components/Dashboard/DailyReportSection/GetMatchedReport/index.tsx
  src/components/Dashboard/DailyReportSection/index.tsx
  src/components/Dashboard/GraphSection/DownloadReport.tsx
  src/components/Dashboard/GraphSection/DownloadReport/CouponCounter/index.tsx
  src/components/Dashboard/GraphSection/DownloadReport/CouponRate/index.tsx
  src/components/Dashboard/GraphSection/DownloadReport/index.tsx
  src/components/Dashboard/GraphSection/GraphContainer.tsx
  src/components/Dashboard/GraphSection/GraphContainer/graphOptions.ts
  src/components/Dashboard/GraphSection/GraphContainer/index.tsx
  src/components/Dashboard/GraphSection/index.tsx
  src/components/Dashboard/LocalInformationSection/LocalCouponUsage/index.tsx
  src/components/Dashboard/LocalInformationSection/Top3Coupons/RankingBox/index.tsx
  src/components/Dashboard/LocalInformationSection/Top3Coupons/index.tsx
  src/components/Dashboard/LocalInformationSection/index.tsx
  src/components/Dashboard/index.tsx
  src/pages/Dashboard/index.tsx
  src/routes/MainRouter/index.tsx
  src/types/dashboard.ts
  src/utils/index.ts
  src/utils/lib/calculation.ts
  src/utils/lib/dashboard.ts
Labels: modify, design

#42 [#34] 로그인/회원가입 페이지 공용 컴포넌트 분리
  src/assets/icons/ic-login-close.svg
  src/assets/icons/ic-login-eye-off.svg
  src/assets/icons/ic-login-eye-on.svg
  src/assets/icons/ic-signup-check-invalid.svg
  src/assets/icons/ic-signup-check-valid.svg
  src/components/Login/LoginForm/index.tsx
  src/components/SignUp/SignUpForm/index.tsx
  src/components/common/Auth/AuthButton/index.tsx
  src/components/common/Auth/AuthInputNormal/index.tsx
  src/components/common/Auth/AuthInputPassword/index.tsx
  src/components/common/Auth/index.tsx
  src/types/auth.ts
  src/types/login.ts
  src/types/signUp.ts
Labels: feat

#36 [#35] theme 컨벤션 수정
  src/types/theme.d.ts
Labels: chore

#39 [#37] 누적 그래프 차트 레이아웃
  src/components/Report/LeftSection/Graph/index.tsx
  src/components/Report/LeftSection/YearReport/index.tsx
  src/components/Report/LeftSection/index.tsx
  src/components/Report/RightSection/TotalReport/index.tsx
  src/components/Report/RightSection/index.tsx
  src/components/common/Layout/index.tsx
Labels: design

#41 [#21] 헤더 유저 프로필 클릭 시 모달 생성
  src/components/common/Footer/index.tsx
  src/components/common/Layout/Header/Select/index.tsx
  src/components/common/Layout/Header/User/UserModal/index.tsx
  src/components/common/Layout/Header/User/index.tsx
  src/components/common/Layout/Header/index.tsx
  src/components/common/Layout/Sidebar/Navigation/Coupon/CouponNav/index.tsx
  src/components/common/Layout/Sidebar/Navigation/Coupon/index.tsx
  src/components/common/Layout/Sidebar/Navigation/CustomNavLink/index.tsx
  src/components/common/Layout/Sidebar/Navigation/Settlements/index.tsx
  src/components/common/Layout/Sidebar/index.tsx
  src/components/common/Layout/index.tsx
  src/types/layout.ts
Labels: feat, design

#45 [#43] 로그인 성공 시 쿠키 저장
  .gitignore
  package-lock.json
  package.json
  src/api/index.ts
  src/api/lib/instance.ts
  src/api/lib/postLogin.ts
  src/components/Login/LoginForm/index.tsx
  src/types/auth.ts
  src/utils/lib/cookies.ts
Labels: feat

#30 [#9] 쿠폰 등록 페이지 레이아웃
  src/App.tsx
  src/assets/icons/ic-register-calendar.svg
  src/assets/icons/ic-register-check.svg
  src/assets/icons/ic-register-toggle.svg
  src/components/Register/Preview/index.tsx
  src/components/Register/StepTitle/index.tsx
  src/components/Register/Stepper/index.tsx
  src/components/Register/StepperController/index.tsx
  src/components/Register/Steps/FirstStep/index.tsx
  src/components/Register/Steps/FourthStep/index.tsx
  src/components/Register/Steps/SecondStep/index.tsx
  src/components/Register/Steps/ThirdStep/index.tsx
  src/components/Register/Steps/index.tsx
  src/components/Register/common/InputAccordion/index.tsx
  src/components/Register/common/InputButton/index.tsx
  src/components/Register/common/InputContainer/index.tsx
  src/components/Register/common/index.tsx
  src/components/Register/index.tsx
  src/pages/Register/DisplayStep/index.tsx
  src/pages/Register/index.tsx
  src/routes/MainRouter/index.tsx
  src/styles/GlobalStyles.tsx
  src/types/register.ts
Labels: design

#46 [#33] 쿠폰 조회 레이아웃 추가 & 일부 객실 리스트 목록 추가
  src/assets/icons/ic-couponlist-delete.svg
  src/assets/icons/ic-couponlist-right.svg
  src/components/CouponList/CouponItem/CouponExpired/index.tsx
  src/components/CouponList/CouponItem/CouponExpose/index.tsx
  src/components/CouponList/CouponItem/CouponStop/index.tsx
  src/components/CouponList/CouponItem/CouponWait/index.tsx
  src/components/CouponList/CouponItem/index.tsx
  src/components/CouponList/CouponMain/index.tsx
  src/components/CouponList/CouponNav/index.tsx
  src/pages/CouponList/index.tsx
  src/types/couponList.ts
Labels: design

#57 [#54] 유저 모달 cookie 정보 사용 및 개선
  src/components/CouponList/CouponItem/CouponExpose/index.tsx
  src/components/common/Layout/Header/User/UserModal/index.tsx
  src/components/common/Layout/Header/User/index.tsx
  src/hooks/index.ts
  src/hooks/lib/useExample.ts
  src/hooks/lib/useOutsideClick.ts
  src/types/layout.ts
Labels: feat, modify

#68 [#51] 쿠폰 조회 API 연결
  src/api/index.ts
  src/api/lib/getCouponList.ts
  src/components/CouponList/CouponHeader/index.tsx
  src/components/CouponList/CouponItem/CouponExpired/index.tsx
  src/components/CouponList/CouponItem/CouponExpose/index.tsx
  src/components/CouponList/CouponItem/CouponStop/index.tsx
  src/components/CouponList/CouponItem/CouponWait/index.tsx
  src/components/CouponList/CouponMain/index.tsx
  src/components/CouponList/CouponNav/index.tsx
  src/recoil/atoms/couponListState.ts
  src/recoil/index.ts
  src/types/couponList.ts
Labels: feat

#55 [#12] 정산페이지 레이아웃 작업 및 더미 데이터를 사용한 기능 구현
  package-lock.json
  package.json
  src/assets/icons/calendar-number-outline.svg
  src/assets/icons/information-circle-outline.svg
  src/assets/icons/receipt-sharp.svg
  src/assets/icons/settlements-admin.svg
  src/assets/icons/settlements-data-frame.svg
  src/assets/icons/settlements-logo.svg
  src/assets/icons/sync-outline.svg
  src/components/Settlements/SettlementsLeft/SettlementsSetting/Settlemented/SettlementsPagination/index.tsx
  src/components/Settlements/SettlementsLeft/SettlementsSetting/Settlemented/SettlementsTable/index.tsx
  src/components/Settlements/SettlementsLeft/SettlementsSetting/Settlemented/index.tsx
  src/components/Settlements/SettlementsLeft/SettlementsSetting/SettlementsHeader/SettlementsPopup/index.tsx
  src/components/Settlements/SettlementsLeft/SettlementsSetting/SettlementsHeader/index.tsx
  src/components/Settlements/SettlementsLeft/SettlementsSetting/index.tsx
  src/components/Settlements/SettlementsLeft/index.tsx
  src/components/Settlements/SettlementsRight/SettlementsBefore/index.tsx
  src/components/Settlements/SettlementsRight/SettlementsExpected/index.tsx
  src/components/Settlements/SettlementsRight/index.tsx
  src/components/Settlements/index.tsx
  src/pages/Settlements/index.tsx
  src/recoil/atoms/settlemented.ts
  src/routes/MainRouter/index.tsx
  src/types/settlements.ts
Labels: feat, design

#60 [#50] API GET 예시 (axios, 리액트 쿼리, 로딩, 에러)
  package-lock.json
  package.json
  src/App.tsx
  src/api/index.ts
  src/api/lib/getExample.ts
  src/api/lib/getTotalReport.ts
  src/api/lib/getYearReport.ts
  src/components/Report/LeftSection/Graph/SelectYear/index.tsx
  src/components/Report/LeftSection/Graph/index.tsx
  src/components/Report/LeftSection/YearReport/index.tsx
  src/components/Report/LeftSection/index.error.tsx
  src/components/Report/LeftSection/index.loading.tsx
  src/components/Report/LeftSection/index.tsx
  src/components/Report/RightSection/TotalReport/index.error.tsx
  src/components/Report/RightSection/TotalReport/index.loading.tsx
  src/components/Report/RightSection/TotalReport/index.tsx
  src/components/Report/RightSection/index.tsx
  src/hooks/index.ts
  src/hooks/queries/useGetExample.ts
  src/hooks/queries/useGetTotalReport.ts
  src/hooks/queries/useGetYearReport.ts
  src/pages/Report/index.tsx
  src/routes/MainRouter/index.tsx
  src/types/report.ts
  src/utils/lib/report.ts
Labels: feat

#61 [#58] privateRouter, publicRouter 설정
  src/components/Login/LoginForm/index.tsx
  src/routes/MainRouter/index.tsx
  src/routes/PrivateRouter/index.tsx
  src/routes/PublicRouter/index.tsx
  src/routes/index.ts
Labels: feat

#72 [#66] 헤더 Select 상태 API 연결
  src/api/index.ts
  src/api/lib/getHeaderAccommodation.ts
  src/api/lib/getTotalReport.ts
  src/components/CouponList/CouponNav/index.tsx
  src/components/Report/LeftSection/index.tsx
  src/components/Report/RightSection/TotalReport/index.tsx
  src/components/common/Layout/Header/Select/index.tsx
  src/hooks/queries/useGetHeaderAccommodation.ts
  src/hooks/queries/useGetTotalReport.ts
  src/hooks/queries/useGetYearReport.ts
  src/recoil/atoms/headerAccommodationState.ts
  src/types/header.ts
  src/types/layout.ts
Labels: feat

#53 [#44] 대시보드 API 연동(1)
  src/api/index.ts
  src/api/lib/getCouponRanking.ts
  src/api/lib/getDailyReport.ts
  src/api/lib/getLocalCouponUsage.ts
  src/api/lib/getMonthReports.ts
  src/api/lib/getMonthStatus.ts
  src/components/Dashboard/DashboardLeftSection/GraphSection/DownloadReport/CouponCounter/index.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/DownloadReport/CouponRate/index.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/DownloadReport/index.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/GraphContainer/graphOptions.ts
  src/components/Dashboard/DashboardLeftSection/GraphSection/GraphContainer/index.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/index.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/LocalCouponUsage/index.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/Top3Coupons/RankingBox/index.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/Top3Coupons/index.error.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/Top3Coupons/index.loading.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/Top3Coupons/index.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/index.tsx
  src/components/Dashboard/DashboardLeftSection/index.tsx
  src/components/Dashboard/DashboardRightSection/CouponStatusSection/StatusItem/index.tsx
  src/components/Dashboard/DashboardRightSection/CouponStatusSection/index.error.tsx
  src/components/Dashboard/DashboardRightSection/CouponStatusSection/index.loading.tsx
  src/components/Dashboard/DashboardRightSection/CouponStatusSection/index.tsx
  src/components/Dashboard/DashboardRightSection/DailyReportSection/GetMatchedReport/index.tsx
  src/components/Dashboard/DashboardRightSection/DailyReportSection/index.error.tsx
  src/components/Dashboard/DashboardRightSection/DailyReportSection/index.loading.tsx
  src/components/Dashboard/DashboardRightSection/DailyReportSection/index.tsx
  src/components/Dashboard/DashboardRightSection/index.tsx
  src/components/Dashboard/dashboardKeyframes.css
  src/components/Dashboard/index.tsx
  src/hooks/queries/useGetCouponRanking.tsx
  src/hooks/queries/useGetDailyReport.tsx
  src/hooks/queries/useGetMonthStatus.ts
  src/pages/Dashboard/index.tsx
  src/types/dashboard.ts
  src/utils/lib/dashboard.ts
Labels: feat, design

#73 [#67] 레이아웃 헤더 select 디자인 수정 (정산 페이지 select 사용, 모바일 화면 작업)
  src/components/common/DashboardHeader/index.tsx
  src/components/common/Layout/Header/Select/index.tsx
  src/components/common/Layout/Header/index.tsx
  src/components/common/Layout/Sidebar/Header/index.tsx
Labels: design

#75 [#74] 누적 리포트 연도 select recoil로 상태 관리
  src/api/lib/getYearReport.ts
  src/components/Report/LeftSection/Graph/SelectYear/index.tsx
  src/components/Report/LeftSection/index.tsx
  src/components/common/Layout/Header/index.tsx
  src/components/common/Layout/index.tsx
  src/hooks/queries/useGetYearReport.ts
  src/recoil/atoms/selectedYearState.ts
  src/recoil/index.ts
  src/utils/index.ts
  src/utils/lib/report.ts
Labels: feat

#82 [#49] 누적 리포트 모바일 반응형 레이아웃
  src/components/Report/LeftSection/Graph/SelectYear/index.tsx
  src/components/Report/LeftSection/Graph/index.tsx
  src/components/Report/LeftSection/YearReport/index.tsx
  src/components/Report/LeftSection/index.error.tsx
  src/components/Report/LeftSection/index.loading.tsx
  src/components/Report/LeftSection/index.tsx
  src/components/Report/RightSection/Catchphrase/index.tsx
  src/components/Report/RightSection/TotalReport/index.error.tsx
  src/components/Report/RightSection/TotalReport/index.loading.tsx
  src/components/Report/RightSection/TotalReport/index.tsx
  src/components/Report/RightSection/index.tsx
  src/components/common/DashboardHeader/index.tsx
  src/components/common/Layout/Header/index.tsx
  src/components/common/Layout/index.tsx
  src/pages/Report/index.tsx
Labels: design

#81 [#76] 대시보드 API 연동(2)
  src/api/lib/getLocalCouponUsage.ts
  src/api/lib/getMonthReports.ts
  src/components/Dashboard/DashboardLeftSection/GraphSection/DownloadReport/CouponCounter/index.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/DownloadReport/index.error.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/DownloadReport/index.loading.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/DownloadReport/index.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/GraphContainer/graphOptions.ts
  src/components/Dashboard/DashboardLeftSection/GraphSection/GraphContainer/index.error.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/GraphContainer/index.loading.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/GraphContainer/index.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/index.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/LocalCouponUsage/index.error.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/LocalCouponUsage/index.loading.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/LocalCouponUsage/index.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/Top3Coupons/index.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/index.tsx
  src/components/Dashboard/DashboardRightSection/CouponStatusSection/index.tsx
  src/components/Dashboard/DashboardRightSection/DailyReportSection/index.tsx
  src/hooks/index.ts
  src/hooks/queries/useGetCouponRanking.ts
  src/hooks/queries/useGetDailyReport.ts
  src/hooks/queries/useGetLocalCouponUsage.ts
  src/hooks/queries/useGetMonthReports.ts
  src/hooks/queries/useGetMonthStatus.ts
  src/types/dashboard.ts
Labels: feat

#79 [#69] 쿠폰 수정 & 삭제 API , 쿠폰 배너 API 구현
  src/api/index.ts
  src/api/lib/getCouponList.ts
  src/components/CouponList/CouponBanner/index.tsx
  src/components/CouponList/CouponHeader/index.tsx
  src/components/CouponList/CouponItem/CouponExpired/index.tsx
  src/components/CouponList/CouponItem/CouponExpose/index.tsx
  src/components/CouponList/CouponItem/CouponStop/index.tsx
  src/components/CouponList/CouponItem/CouponWait/index.tsx
  src/components/CouponList/CouponMain/index.tsx
  src/components/CouponList/CouponNav/index.tsx
  src/components/modal/index.tsx
  src/hooks/index.ts
  src/hooks/queries/useCouponList.ts
  src/types/couponList.ts
  src/utils/lib/couponCondition.ts
Labels: feat

#91 [#83] 누적 리포트 QA 피드백 반영
  src/assets/icons/ic-error.svg
  src/assets/icons/ic-reload.svg
  src/components/Report/LeftSection/Graph/SelectYear/index.tsx
  src/components/Report/LeftSection/Graph/index.tsx
  src/components/Report/LeftSection/index.error.tsx
  src/components/Report/RightSection/TotalReport/index.error.tsx
  src/components/Report/RightSection/TotalReport/index.tsx
  src/components/common/Layout/Header/User/UserModal/index.tsx
  src/components/common/Layout/Header/User/index.tsx
  src/components/common/MobileDashboardHeader/index.tsx
  src/pages/Report/index.tsx
  src/recoil/atoms/selectedYearState.ts
  src/types/layout.ts
Labels: feat, modify, fix

#89 [#62] react-hook-form 설치 및 유효성 검사 로직
  package-lock.json
  package.json
  src/components/Auth/AuthButton/index.tsx
  src/components/Auth/AuthInputNormal/index.tsx
  src/components/Auth/AuthInputPassword/index.tsx
  src/components/Auth/index.tsx
  src/components/Login/LoginForm/index.tsx
  src/components/SignUp/SignUpForm/index.tsx
  src/types/auth.ts
  src/types/login.ts
  src/types/signUp.ts
  src/utils/index.ts
  src/utils/lib/auth.ts
Labels: feat

#97 [#96] 로그인 유효성 검사 로직 수정
  src/components/Login/LoginForm/index.tsx
  src/utils/lib/auth.ts
Labels: modify

#100 [#93] 메타 데이터 추가
  index.html
  public/favicon.ico
  public/og-image-800x400.png
  src/assets/icons/ic-logo.svg
  src/assets/icons/ic-sidebar-settlement.svg
Labels: feat

#101 [#86] 대시보드 모바일 반응형 적용
  src/components/Dashboard/DashboardLeftSection/GraphSection/DownloadReport/CouponCounter/index.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/DownloadReport/CouponRate/index.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/DownloadReport/index.loading.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/DownloadReport/index.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/GraphContainer/graphOptions.ts
  src/components/Dashboard/DashboardLeftSection/GraphSection/GraphContainer/index.loading.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/GraphContainer/index.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/index.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/LocalCouponUsage/index.loading.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/LocalCouponUsage/index.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/Top3Coupons/RankingBox/index.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/Top3Coupons/index.loading.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/Top3Coupons/index.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/index.tsx
  src/components/Dashboard/DashboardLeftSection/index.tsx
  src/components/Dashboard/DashboardRightSection/CouponStatusSection/StatusItem/index.tsx
  src/components/Dashboard/DashboardRightSection/CouponStatusSection/index.error.tsx
  src/components/Dashboard/DashboardRightSection/CouponStatusSection/index.loading.tsx
  src/components/Dashboard/DashboardRightSection/CouponStatusSection/index.tsx
  src/components/Dashboard/DashboardRightSection/DailyReportSection/GetMatchedReport/index.tsx
  src/components/Dashboard/DashboardRightSection/DailyReportSection/index.loading.tsx
  src/components/Dashboard/DashboardRightSection/DailyReportSection/index.tsx
  src/components/Dashboard/DashboardRightSection/index.tsx
  src/pages/Dashboard/index.tsx
Labels: design

#99 [#92] 전체 레이아웃 에러 및 로딩화면 개선
  src/App.error.tsx
  src/App.loading.tsx
  src/components/common/Layout/Header/Select/index.tsx
  src/components/common/Layout/Sidebar/Header/index.tsx
  src/components/common/Layout/Sidebar/index.tsx
  src/components/common/MobileDashboardHeader/index.tsx
Labels: feat, design

#103 [#102] 로그아웃 API 연결
  src/api/index.ts
  src/api/lib/instance.ts
  src/api/lib/postLogout.ts
  src/components/common/Layout/Header/User/UserModal/index.tsx
  src/constants/lib/ERROR_MODAL_MESSAGE.ts
  src/pages/Login/index.tsx
  src/utils/index.ts
  src/utils/lib/cookies.ts
Labels: feat

#105 [#95] 회원가입 관련 API 연결 및 로그인 관련 추가 API 로직 수정
  src/api/index.ts
  src/api/lib/getEmailValid.ts
  src/api/lib/instance.ts
  src/api/lib/postSignUp.ts
  src/assets/icons/ic-signup-firecracker.svg
  src/components/Login/LoginForm/index.tsx
  src/components/SignUp/SignUpForm/index.tsx
  src/components/common/Layout/Header/User/UserModal/index.tsx
  src/constants/index.ts
  src/constants/lib/ERROR_MODAL_MESSAGE.ts
  src/pages/Login/index.tsx
  src/pages/SignUp/index.tsx
  src/pages/SignUpComplete/index.tsx
  src/routes/MainRouter/index.tsx
  src/routes/PrivateRouter/index.tsx
  src/types/signUp.ts
Labels: feat

#77 [#70] 정산페이지 api 연결
  package-lock.json
  package.json
  src/api/index.ts
  src/api/lib/getSettlemented.ts
  src/api/lib/getSettlements.ts
  src/components/Settlements/SettlementsLeft/SettlementsSetting/Settlemented/SettlementsPagination/index.tsx
  src/components/Settlements/SettlementsLeft/SettlementsSetting/Settlemented/SettlementsTable/index.tsx
  src/components/Settlements/SettlementsLeft/SettlementsSetting/Settlemented/index.error.tsx
  src/components/Settlements/SettlementsLeft/SettlementsSetting/Settlemented/index.loading.tsx
  src/components/Settlements/SettlementsLeft/SettlementsSetting/Settlemented/index.tsx
  src/components/Settlements/SettlementsLeft/SettlementsSetting/SettlementsHeader/SettlementsPopup/index.tsx
  src/components/Settlements/SettlementsLeft/SettlementsSetting/SettlementsHeader/index.tsx
  src/components/Settlements/SettlementsLeft/SettlementsSetting/index.tsx
  src/components/Settlements/SettlementsLeft/index.tsx
  src/components/Settlements/SettlementsRight/SettlementsBefore/index.error.tsx
  src/components/Settlements/SettlementsRight/SettlementsBefore/index.loading.tsx
  src/components/Settlements/SettlementsRight/SettlementsBefore/index.tsx
  src/components/Settlements/SettlementsRight/SettlementsExpected/index.tsx
  src/components/Settlements/SettlementsRight/index.tsx
  src/constants/lib/SETTLEMENTS_TABLE_KEY.ts
  src/hooks/queries/useGetSettlemented.ts
  src/hooks/queries/useGetSettlements.ts
  src/pages/Settlements/index.tsx
  src/recoil/atoms/settlemented.ts
  src/types/settlements.ts
Labels: feat

#108 [#106] 로그인/회원가입 모바일 레이아웃 & 회원가입 완료 페이지를 컴포넌트로 변경
  src/components/Auth/AuthButton/index.tsx
  src/components/Auth/AuthInputNormal/index.tsx
  src/components/Auth/AuthInputPassword/index.tsx
  src/components/Login/LoginForm/index.tsx
  src/components/Login/LoginTitle/index.tsx
  src/components/SignUp/SignUpComplete/index.tsx
  src/components/SignUp/SignUpForm/index.tsx
  src/components/SignUp/SignUpTitle/index.tsx
  src/components/SignUp/index.tsx
  src/components/common/ErrorModal/index.tsx
  src/pages/Login/index.tsx
  src/pages/SignUp/index.tsx
  src/routes/MainRouter/index.tsx
  src/types/signUp.ts
Labels: feat, design

#115 [#63] 입력값 유효성 검사 및 전역 상태 관리
  src/assets/icons/ic-register-calendar-selected.svg
  src/components/Register/Preview/index.tsx
  src/components/Register/StepTitle/index.tsx
  src/components/Register/Stepper/index.tsx
  src/components/Register/StepperController/index.tsx
  src/components/Register/Steps/FirstStep/index.tsx
  src/components/Register/Steps/FourthStep/Calendar/index.tsx
  src/components/Register/Steps/FourthStep/index.tsx
  src/components/Register/Steps/SecondStep/RoomList/index.tsx
  src/components/Register/Steps/SecondStep/RoomSelectButton/index.tsx
  src/components/Register/Steps/SecondStep/RoomSelectModal/index.tsx
  src/components/Register/Steps/SecondStep/index.tsx
  src/components/Register/Steps/ThirdStep/RadioGroup/Radio/index.tsx
  src/components/Register/Steps/ThirdStep/RadioGroup/index.tsx
  src/components/Register/Steps/ThirdStep/index.tsx
  src/components/Register/common/ErrorMessage/index.tsx
  src/components/Register/common/InputAccordion/index.tsx
  src/components/Register/common/InputButton/index.tsx
  src/components/Register/common/InputCheckBox/index.tsx
  src/components/Register/common/InputField/index.tsx
  src/components/Register/common/InputRadio/index.tsx
  src/components/Register/common/InputWrapper/index.tsx
  src/components/Register/common/index.tsx
  src/components/common/index.tsx
  src/hooks/index.ts
  src/hooks/lib/useStepValidation.ts
  src/pages/Register/index.tsx
  src/recoil/atoms/previewState.ts
  src/recoil/atoms/registerInputState.ts
  src/recoil/atoms/registerValidState.ts
  src/recoil/index.ts
  src/types/register.ts
  src/utils/index.ts
  src/utils/lib/getStepperConfig.ts
  src/utils/lib/handleStepLessThan3.ts
  src/utils/lib/showValidationMessage.ts
  src/utils/lib/validationUtils.ts
Labels: feat, design

#116 [#111] 대시보드 QA 결과 반영
  src/components/Dashboard/DashboardLeftSection/GraphSection/DownloadReport/index.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/GraphContainer/graphOptions.ts
  src/components/Dashboard/DashboardLeftSection/GraphSection/GraphContainer/index.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/index.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/Top3Coupons/index.tsx
  src/components/Dashboard/DashboardRightSection/DailyReportSection/GetMatchedReport/index.tsx
  src/components/Dashboard/DashboardRightSection/index.tsx
  src/utils/lib/calculation.ts
Labels: design, fix

#113 [#112] 누적 리포트 QA 이슈 해결
  public/images/ic-sidebar-settlement.png
  src/api/lib/getHeaderAccommodation.ts
  src/components/Report/LeftSection/Graph/SelectYear/index.tsx
  src/components/Report/LeftSection/YearReport/index.tsx
  src/components/Report/LeftSection/index.context.ts
  src/components/Report/LeftSection/index.tsx
  src/components/Report/RightSection/TotalReport/index.tsx
  src/components/common/Layout/Header/Select/index.tsx
  src/components/common/Layout/Header/User/UserModal/index.tsx
  src/components/common/Layout/Sidebar/Navigation/Settlements/index.tsx
  src/components/common/Layout/Sidebar/index.tsx
  src/components/common/Layout/index.tsx
Labels: fix

#144 [#117] 대시보드 에러바운더리 UI추가
  src/components/Dashboard/DashboardLeftSection/GraphSection/DownloadReport/CouponRate/index.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/DownloadReport/index.error.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/GraphContainer/index.error.tsx
  src/components/Dashboard/DashboardLeftSection/GraphSection/index.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/LocalCouponUsage/index.error.tsx
  src/components/Dashboard/DashboardLeftSection/LocalInformationSection/Top3Coupons/index.error.tsx
  src/components/Dashboard/DashboardRightSection/CouponStatusSection/StatusItem/index.tsx
  src/components/Dashboard/DashboardRightSection/CouponStatusSection/index.error.tsx
  src/components/Dashboard/DashboardRightSection/CouponStatusSection/index.tsx
  src/components/Dashboard/DashboardRightSection/DailyReportSection/index.error.tsx
  src/components/Dashboard/DashboardRightSection/index.tsx
Labels: feat, design, fix

#146 [#127] 정산페이지 QA 추가 문제
  src/assets/icons/settlements-admin.svg
  src/components/Settlements/SettlementsLeft/SettlementsSetting/Settlemented/index.error.tsx
  src/components/Settlements/SettlementsLeft/SettlementsSetting/Settlemented/index.loading.tsx
  src/components/Settlements/SettlementsLeft/SettlementsSetting/Settlemented/index.tsx
  src/components/Settlements/SettlementsLeft/SettlementsSetting/SettlementsHeader/index.tsx
  src/components/Settlements/SettlementsLeft/SettlementsSetting/index.tsx
Labels: feat, design, fix

#141 [#134] 등록 페이지 QA 수정사항 반영
  src/components/Register/Steps/FirstStep/index.tsx
  src/components/Register/Steps/SecondStep/RoomSelectModal/index.tsx
  src/components/Register/Steps/SecondStep/index.tsx
  src/components/Register/common/InputAccordion/index.tsx
  src/types/register.ts
  src/utils/lib/showValidationMessage.ts
Labels: modify, fix

#162 [#142] 등록 페이지 반응형 디자인
  src/components/Register/Preview/index.tsx
  src/components/Register/StepTitle/index.tsx
  src/components/Register/Stepper/index.tsx
  src/components/Register/StepperController/index.tsx
  src/components/Register/Steps/FirstStep/index.tsx
  src/components/Register/Steps/FourthStep/Calendar/index.tsx
  src/components/Register/Steps/FourthStep/RegisterCompleteModal/index.tsx
  src/components/Register/Steps/FourthStep/index.tsx
  src/components/Register/Steps/SecondStep/RoomList/index.tsx
  src/components/Register/Steps/SecondStep/RoomSelectButton/index.tsx
  src/components/Register/Steps/SecondStep/RoomSelectModal/index.tsx
  src/components/Register/Steps/SecondStep/index.tsx
  src/components/Register/Steps/ThirdStep/RadioGroup/Radio/index.tsx
  src/components/Register/Steps/ThirdStep/index.tsx
  src/components/Register/common/ErrorMessage/index.tsx
  src/components/Register/common/InputAccordion/index.tsx
  src/components/Register/common/InputButton/index.tsx
  src/components/Register/common/InputCheckBox/index.tsx
  src/components/Register/common/InputContainer/index.tsx
  src/components/Register/common/InputField/index.tsx
  src/components/Register/common/InputRadio/index.tsx
  src/components/Register/common/InputWrapper/index.tsx
  src/pages/Register/index.tsx
  src/types/register.ts
Labels: design

#161 [#160] 사장님 비서 Ya product 배포 (v1.0.0)
  README.md
  src/api/lib/instance.ts
  src/components/Register/Preview/index.tsx
  src/components/Register/StepTitle/index.tsx
  src/components/Register/Stepper/index.tsx
  src/components/Register/StepperController/index.tsx
  src/components/Register/Steps/FirstStep/index.tsx
  src/components/Register/Steps/FourthStep/Calendar/index.tsx
  src/components/Register/Steps/FourthStep/RegisterCompleteModal/index.tsx
  src/components/Register/Steps/FourthStep/index.tsx
  src/components/Register/Steps/SecondStep/RoomList/index.tsx
  src/components/Register/Steps/SecondStep/RoomSelectButton/index.tsx
  src/components/Register/Steps/SecondStep/RoomSelectModal/index.tsx
  src/components/Register/Steps/SecondStep/index.tsx
  src/components/Register/Steps/ThirdStep/RadioGroup/Radio/index.tsx
  src/components/Register/Steps/ThirdStep/index.tsx
  src/components/Register/common/ErrorMessage/index.tsx
  src/components/Register/common/InputAccordion/index.tsx
  src/components/Register/common/InputButton/index.tsx
  src/components/Register/common/InputCheckBox/index.tsx
  src/components/Register/common/InputContainer/index.tsx
  src/components/Register/common/InputField/index.tsx
  src/components/Register/common/InputRadio/index.tsx
  src/components/Register/common/InputWrapper/index.tsx
  src/components/common/Layout/Header/MobileSidebar/OpenMobileSidebar/index.tsx
  src/pages/Register/index.tsx
  src/types/register.ts
  src/utils/lib/showValidationMessage.ts
Labels: feat, fix
